version: "3.9"
services:
  app:
    build: .
    ports:
    - "5000:5000"
    environment:
    - REDIS_HOST=${REDIS_HOST}
    - REDIS_PORT=${REDIS_PORT}
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    links:
    - redis
    restart: unless-stopped
  redis:
    image: redis
    restart: unless-stopped

    
