{{- if .Values.ingress.enabled -}}
{{- $fullName := include "keep-counter.fullname"  . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "keep-counter.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - pathType: ImplementationSpecific
            path: {{ .path }}
            backend:
              service:
                name: {{ $fullName }}-flask
                port:
                  number: 5000
        {{- end }}
  {{- end }}
{{- end }}
