apiVersion: v1
kind: Service
metadata:
  name: {{ include "keep-counter.fullname" . }}-redis
  labels:
    {{- include "keep-counter.labels" . | nindent 4 }}-redis
spec:
  type: {{ .Values.service.redis.type }}
  ports:
    - port: {{ .Values.service.redis.port }}
      targetPort: 6379
      protocol: TCP
  selector:
    {{- include "keep-counter.selectorLabels" . | nindent 4 }}-redis
    