# Default values for keep-counter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


secret:
  data:
    password: MWYyZDFlMmU2N2Rm


replicaCount: 1



deployment:
  flask:
    port: 5000
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "200Mi"
        cpu: "200m"
    image:
      repository: leosn/keep-counter
      tag: "4.0"
  redis:
    port: 6379
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    image: redis:alpine


service:
  flask:
    type: ClusterIP
    port: 5000
  redis:
    type: ClusterIP
    port: 6379
    

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: flask.34-132-94-3.nip.io
      paths:
        - path: "/"
          
  tls: []    


data:
  redis_host: redis
  