---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Filebeat.
  package:
    name: "{{ filebeat_package }}"
    state: "{{ filebeat_package_state }}"

- include: config.yml
  when: filebeat_create_config | bool

# Enables system, nginx and mysql modules
- name: Enable filebeat modules nginx & system
  shell: filebeat modules enable system nginx mysql
  become: true

- name: Ensure Filebeat is started and enabled at boot.
  service:
    name: filebeat
    state: started
    enabled: true
