# Default values for counter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  name: leosn/keep-counter
  tag: "3.0"

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000


ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: flask.34-132-94-3.nip.io
      paths:
        - path: "/"
          
  tls: []

resources: 
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70



redis: 
  cluster:
    enabled: false
  metrics:
    enabled: true                
