# Default values for fastapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# image:
#   repository: leosn/fast-api
#   pullPolicy: IfNotPresent
#   # Overrides the image tag whose default is the chart appVersion.
#   tag: "0.0.2"

image:
  repository: ghcr.io/bylijoe/liberando-productos-leosilva
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# imagePullSecrets created to use GitHub Private Account
# imagePullSecrets:
#   - name: dockerconfigjson-github-com

# # -- imageCredentials for GitHub private account
# imageCredentials:
#   ## -- GitHub registry URL
#   registry:  "ghcr.io"
#   ## -- GitHub account's username
#   username: "bylijoe"
#   ## -- GitHub account's token (only read permissions)
#   password: "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"



serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations:
  reloader.stakater.com/auto: "true"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000



## -- Metrics configuration of the application to deploy
metrics:
  # -- Indicates whether this app will expose metrics
  enabled: true
  # -- Service configuration used for metrics
  svc:
    # -- Service port number used for metrics
    port: 8000
    # -- Service port name used for metrics
    name: metrics


service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 30

nodeSelector: {}

tolerations: []

affinity: {}
