apiVersion: v1
kind: Service
metadata:
  name: {{ include "counter.fullname" . }}-flask
  labels:
    {{- include "counter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targertPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "counter.selectorLabels" . | nindent 4 }}
